apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: streams.awsservices.k8s.io
spec:
  group: awsservices.k8s.io
  preserveUnknownFields: false
  names:
    kind: Stream
    listKind: StreamList
    plural: streams
    singular: stream
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: represents kinesis stream
      type: object
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CertificateSpec defines the desired state of Certificate. A
            valid Certificate requires at least one of a CommonName, DNSName, or URISAN
            to be valid.
          type: object
          required:
          - streamName
          - shardCount
          - tags
          properties:
            streamName:
              description: represents kinesis stream name
              type: string
            shardCount:
              description: represents shard counts for kinesis stream
              type: integer
            tags:
              type: array
              items:
                description: tags for stream
                type: object
                properties:
                  tagKey:
                    description: tag key
                    type: string
                  tagValue:
                    description: tag value
                    type: string
        status:
          description: status of kinesis stream
          type: object
          properties:
            retentionPeriodHours:
              description: holds retention period in hours in stream
              type: integer
            streamARN:
              description: streams ARN information
              type: string
            streamName:
              description: stream name from aws service
              type: string
            streamStatus:
              description: stream status
              type: string
            encryptionType:
              description: encryption type used for stream
              type: string
            keyId:
              description: kms key used for encryption
              type: string
            shards:
              type: array
              items:
                description: shards in the stream
                type: object
                properties:
                  hashKeyRange:
                    description: describes hash key range
                    type: object
                    properties:
                      startingHashKey:
                        description: starting hash key
                        type: string
                      endingHashKey:
                        description: ending hash key
                        type: string
                  sequenceNumberRange:
                    description: sequence number range
                    type: object
                    properties:
                      startingSequenceNumber:
                        description: starting sequence number
                        type: string
                      endingSequenceNumber:
                        description: ending sequence number
                        type: string
                  shardId:
                    description: shared id
                    type: string
                  adjacentParentShardId:
                    description: adjacent parent shard id
                    type: string
                  parentShardId:
                    description: parent shard id
                    type: string
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true