apiVersion: awsservices.k8s.io/v1alpha1
kind: Stream
metadata:
  name: anilkal-test-stream-1
  namespace: cloud-ops1
spec:
  streamName: anilkal-test-stream-1
  shardCount: 1
  tags:
  - tagKey: owner
    tagValue: anilkal
  - tagKey: namespace
    tagValue: cloud-ops1