{{- if .Values.aws_services_stream.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aws-services.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "aws-services.name" . }}
    helm.sh/chart: {{ include "aws-services.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "aws-services.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "aws-services.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        configHash: {{ include "aws-services.configHash" . }}
    spec:
      serviceAccountName: {{ include "aws-services.serviceAccountName" . }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "aws-services.name" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - /go/bin/aws-services-stream
          - --v=4
          volumeMounts:
          - name: config-volume
            mountPath: /config/
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            {{ toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{ toYaml .Values.readinessProbe | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{ end }}