{{- if .Values.aws_services_stream.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "aws-services.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "aws-services.name" . }}
    helm.sh/chart: {{ include "aws-services.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{ end }}